export interface GroupScaffold {
  name: string;
  bgHexColor: string;
  products: string[];
}

export const RecipeGroupScaffold: GroupScaffold[] = [
  {
    name: 'Iron',
    bgHexColor: '#BFBFBF',
    products: [
      'desc-ironingot-c',
      'desc-ironplate-c',
      'desc-ironrod-c',
      'desc-ironscrew-c',
      'desc-ironplatereinforced-c',
    ],
  },
  {
    name: 'Copper',
    bgHexColor: '#FDE3D6',
    products: [
      'desc-copperingot-c',
      'desc-coppersheet-c',
      'desc-wire-c',
      'desc-cable-c',
      'desc-copperdust-c',
    ],
  },
  {
    name: 'Caterium',
    bgHexColor: '#FFE59A',
    products: ['desc-goldingot-c', 'desc-highspeedwire-c'],
  },
  {
    name: 'Concrete',
    bgHexColor: '#FFF2CD',
    products: ['desc-cement-c'],
  },
  {
    name: 'Steel',
    bgHexColor: '#808080',
    products: [
      'desc-steelingot-c',
      'desc-steelpipe-c',
      'desc-steelplate-c',
      'desc-steelplatereinforced-c',
    ],
  },
  {
    name: 'Biofuel',
    bgHexColor: '#996533',
    products: [
      'desc-genericbiomass-c',
      'desc-biofuel-c',
      'desc-liquidbiofuel-c',
      'desc-coal-c',
    ],
  },
  {
    name: 'Native Fauna',
    bgHexColor: '#8E0048',
    products: ['desc-alienprotein-c', 'desc-aliendnacapsule-c'],
  },
  {
    name: 'Quartz',
    bgHexColor: '#FECCFF',
    products: ['desc-quartzcrystal-c', 'desc-silica-c'],
  },
  {
    name: 'SAM',
    bgHexColor: '#7030A0',
    products: [
      'desc-samingot-c',
      'desc-samfluctuator-c',
      'desc-alienpowerfuel-c',
    ],
  },
  {
    name: 'Frames',
    bgHexColor: '#D9E2F3',
    products: [
      'desc-modularframe-c',
      'desc-modularframeheavy-c',
      'desc-modularframefused-c',
      'desc-pressureconversioncube-c',
    ],
  },
  {
    name: 'Motors',
    bgHexColor: '#2E5495',
    products: [
      'desc-rotor-c',
      'desc-stator-c',
      'desc-motor-c',
      'desc-motorlightweight-c',
    ],
  },
  {
    name: 'Oil',
    bgHexColor: '#404040',
    products: [
      'desc-heavyoilresidue-c',
      'desc-polymerresin-c',
      'desc-plastic-c',
      'desc-rubber-c',
      'desc-petroleumcoke-c',
    ],
  },
  {
    name: 'Fuel',
    bgHexColor: '#FBB74F',
    products: [
      'desc-compactedcoal-c',
      'desc-liquidfuel-c',
      'desc-fuel-c',
      'desc-liquidturbofuel-c',
      'desc-rocketfuel-c',
      'desc-ionizedfuel-c',
      'desc-battery-c',
    ],
  },
  {
    name: 'Electronics',
    bgHexColor: '#538136',
    products: [
      'desc-circuitboard-c',
      'desc-circuitboardhighspeed-c',
      'desc-crystaloscillator-c',
      'desc-computer-c',
      'desc-highspeedconnector-c',
      'desc-modularframelightweight-c',
      'desc-computersuper-c',
    ],
  },
  {
    name: 'Aluminum',
    bgHexColor: '#F2F2F2',
    products: [
      'desc-aluminasolution-c',
      'desc-aluminumscrap-c',
      'desc-aluminumingot-c',
      'desc-aluminumcasing-c',
      'desc-aluminumplate-c',
      'desc-aluminumplatereinforced-c',
      'desc-coolingsystem-c',
    ],
  },
  {
    name: 'Munitions',
    bgHexColor: '#993400',
    products: [
      'desc-gunpowder-c',
      'desc-gunpowdermk2-c',
      'desc-spikedrebar-c',
      'desc-rebar-spreadshot-c',
      'desc-rebar-explosive-c',
      'desc-cartridgestandard-c',
      'desc-cartridgechaos-c',
      'desc-cartridgesmartprojectile-c',
      'desc-nobeliskexplosive-c',
      'desc-nobeliskgas-c',
      'desc-nobeliskshockwave-c',
      'desc-nobelisknuke-c',
      'desc-nobeliskcluster-c',
      'desc-rebar-stunshot-c',
    ],
  },
  {
    name: 'Quantum',
    bgHexColor: '#660066',
    products: [
      'desc-darkenergy-c',
      'desc-timecrystal-c',
      'desc-darkmatter-c',
      'desc-singularitycell-c',
      'desc-quantumoscillator-c',
      'desc-temporalprocessor-c',
    ],
  },
  {
    name: 'Power Shards',
    bgHexColor: '#39A5CE',
    products: ['desc-crystalshard-c'],
  },
  {
    name: 'Acids',
    bgHexColor: '#FED966',
    products: ['desc-sulfuricacid-c', 'desc-nitricacid-c'],
  },
  {
    name: 'Nuclear',
    bgHexColor: '#93D14F',
    products: [
      'desc-uraniumcell-c',
      'desc-electromagneticcontrolrod-c',
      'desc-nuclearfuelrod-c',
      'desc-nonfissibleuranium-c',
      'desc-plutoniumpellet-c',
      'desc-plutoniumcell-c',
      'desc-plutoniumfuelrod-c',
      'desc-ficsonium-c',
      'desc-ficsoniumfuelrod-c',
    ],
  },
  {
    name: 'Packaging',
    bgHexColor: '#DEEAF6',
    products: ['desc-fluidcanister-c', 'desc-gastank-c'],
  },
  {
    name: 'Ore Conversions',
    bgHexColor: '#808080',
    products: [
      'desc-oreiron-c',
      'desc-stone-c',
      'desc-orecopper-c',
      'desc-oregold-c',
      'desc-rawquartz-c',
      'desc-sulfur-c',
      'desc-oreuranium-c',
      'desc-orebauxite-c',
      'desc-nitrogengas-c',
    ],
  },
  {
    name: 'Space Elevator',
    bgHexColor: '#000000',
    products: [
      'desc-spaceelevatorpart-1-c',
      'desc-spaceelevatorpart-2-c',
      'desc-spaceelevatorpart-3-c',
      'desc-spaceelevatorpart-4-c',
      'desc-spaceelevatorpart-5-c',
      'desc-spaceelevatorpart-6-c',
      'desc-spaceelevatorpart-7-c',
      'desc-spaceelevatorpart-8-c',
      'desc-spaceelevatorpart-9-c',
      'desc-spaceelevatorpart-10-c',
      'desc-spaceelevatorpart-11-c',
      'desc-spaceelevatorpart-12-c',
    ],
  },
  {
    name: 'Ficsite',
    bgHexColor: '#FEA229',
    products: ['desc-ficsiteingot-c', 'desc-ficsitemesh-c'],
  },
  {
    name: 'Diamonds',
    bgHexColor: '#F2F2F2',
    products: ['desc-diamond-c'],
  },
];
